# Generated by Django 3.2.25 on 2025-04-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250408_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='contact_info',
            field=models.TextField(default=0, verbose_name='联系方式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='experience',
            field=models.TextField(default='', verbose_name='养宠经验'),
            preserve_default=False,
        ),
    ]
