# Generated by Django 3.2.25 on 2025-05-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('event_date', models.DateTimeField(verbose_name='活动时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='活动图片')),
            ],
            options={
                'verbose_name': '救助活动',
                'verbose_name_plural': '救助活动列表',
                'ordering': ['-event_date'],
            },
        ),
    ]
