# Generated by Django 3.2.25 on 2025-05-05 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': '救助活动', 'verbose_name_plural': '救助活动列表'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 21, 21, 41, 257727), verbose_name='结束时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 21, 21, 58, 942295), verbose_name='开始时间'),
            preserve_default=False,
        ),
    ]
