# Generated by Django 3.2.25 on 2025-03-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, verbose_name='详细描述'),
        ),
        migrations.AddField(
            model_name='pet',
            name='health_status',
            field=models.TextField(blank=True, verbose_name='健康描述'),
        ),
    ]
