# Generated by Django 3.2.25 on 2025-03-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20250323_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_adopted',
            field=models.BooleanField(default=False, verbose_name='是否被领养'),
        ),
    ]
