# Generated by Django 3.2.25 on 2025-03-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', '可领养'), ('adopted', '已领养'), ('medical', '医疗中')], default='available', max_length=20, verbose_name='状态'),
        ),
    ]
