# Generated by Django 3.2.25 on 2025-03-27 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='宠物被收容的日期', verbose_name='收容日期'),
        ),
    ]
