# Generated by Django 3.2.25 on 2025-05-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_published', models.BooleanField(default=True, verbose_name='发布状态')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告列表',
            },
        ),
    ]
